
# Generated by https://quicktype.io

from typing import Optional


class CountryByCapitalElement:
    country: str
    city: Optional[str]

    def __init__(self, country: str, city: Optional[str]) -> None:
        self.country = country
        self.city = city
